# Generated by Django 3.2.4 on 2023-07-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.PositiveSmallIntegerField()),
                ('current_floor', models.PositiveSmallIntegerField()),
                ('current_status', models.IntegerField(choices=[(1, 'Going Up'), (0, 'Standing Still'), (-1, 'Going Down')], default=0)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_city', models.CharField(max_length=100)),
                ('building_state', models.CharField(max_length=100)),
                ('number_of_floors', models.PositiveSmallIntegerField()),
                ('elevators_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.PositiveSmallIntegerField()),
                ('elevator_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorsystem'),
        ),
    ]
