# Generated by Django 3.2.4 on 2023-07-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevatorrequest',
            old_name='elevator_system',
            new_name='elevator',
        ),
    ]
